# golangci-lint configuration for MCP YardGopher
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Default linters (enabled by default)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional useful linters
    - bodyclose
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace

  disable:
    - funlen
    - godox
    - godot

formatters:
  enable:
    - gofmt
    - goimports