name: Bug Report
description: Create a detailed bug report to help us improve the DuckDB GORM driver
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: driver-version
    attributes:
      label: Driver Version
      description: Which version of the DuckDB GORM driver are you using?
      placeholder: e.g., v0.2.1
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Blocker (prevents all functionality)
        - Critical (major functionality broken)
        - Major (important functionality broken)
        - Minor (small issue or inconvenience)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Issue Summary
      description: Provide a clear and concise description of the bug
      placeholder: Describe what the bug is...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide your environment information
      value: |
        - Go Version: 
        - GORM Version: 
        - DuckDB Driver Version: 
        - DuckDB Bindings: 
        - Operating System: 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: error-details
    attributes:
      label: Error Details
      description: Include the complete stack trace and error messages
      placeholder: |
        Paste the complete stack trace here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: models
    attributes:
      label: Model Definitions
      description: Include the Go struct definitions that are involved
      placeholder: |
        type YourModel struct {
            // Include complete model definition
        }
      render: go
    validations:
      required: false

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue
      value: |
        1. Setup:
           ```bash
           # Commands to set up the issue
           ```

        2. Run:
           ```bash
           # Commands to reproduce the bug
           ```

        3. Observe:
           - What happens when you run the above

        4. Minimal Example:
           ```go
           package main
           
           import (
               "gorm.io/gorm"
               duckdb "gorm.io/driver/duckdb"
           )
           
           func main() {
               // Minimal code that reproduces the issue
           }
           ```
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Assessment
      description: Check all that apply to your situation
      options:
        - label: Application startup fails
        - label: Database operations don't work
        - label: Migration/AutoMigrate fails
        - label: Performance issues
        - label: Data corruption or loss
        - label: Extension loading problems

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds Attempted
      description: What have you tried to work around this issue?
      placeholder: |
        1. **Approach 1:** [What you tried] → [Result]
        2. **Approach 2:** [What you tried] → [Result]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Configuration, extensions used, performance context, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues for similar problems
          required: true
        - label: I have provided a minimal reproduction case
          required: true
        - label: I have included all relevant version information
          required: true
        - label: I have described the expected vs actual behavior
          required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution Willingness
      description: Are you willing to help fix this issue?
      options:
        - "Yes, I can implement a fix"
        - "Yes, I can help with testing"
        - "Yes, I can help with documentation"
        - "Maybe, depending on complexity"
        - "No, I need someone else to fix this"
    validations:
      required: false
