name: Feature Request
description: Suggest an enhancement or new feature for the DuckDB GORM driver
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand what you'd like to see.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature you'd like to see
      placeholder: Describe the feature in one or two sentences...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful? What problem does it solve?
      placeholder: Explain the use case and benefits...
    validations:
      required: true

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the feature
      placeholder: Explain how the feature should work...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: Proposed API Design
      description: Show how the feature would be used
      placeholder: |
        ```go
        // Show how the feature would be used
        ```
      render: go
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this would be helpful
      value: |
        1. **Use Case 1:** [Describe a specific scenario]
        2. **Use Case 2:** [Describe another scenario]
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Show before/after examples if applicable
      value: |
        ### Current State
        ```go
        // How things work currently
        ```

        ### With Feature
        ```go
        // How things would work with the feature
        ```
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
      placeholder: Describe alternative solutions you've thought about...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking current work)
        - High (would significantly improve workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: How can you help with this feature?
      options:
        - label: I'm willing to implement this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I need someone else to implement this

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or links
      placeholder: Additional information that might be helpful...
    validations:
      required: false
